spring.application.name=api

# PRÁTICA 3: PROTEÇÃO DE CREDENCIAIS DE INFRAESTRUTURA (VARIÁVEIS DE AMBIENTE)
# Nenhuma credencial ou dado literal existe no código-fonte.
spring.datasource.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
spring.datasource.username=${DB_HACKGOV_USER}
spring.datasource.password=${DB_HACKGOV_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Configurações do Hibernate/JPA
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none